#!/bin/bash

# Liscenced under GPL-v3
# Author : UzutoNarumaki
# Original Name : multi-from-list-hayai
# Deps : fzf,ariac,xmlstarlet
# This script fetches link with title so its hayai!

version=0.4

# List of RSS URLs
RSS_URLS=(
"https://nyaa.si/?page=rss&q=erai+hevc&c=1_2&f=0"
"https://nyaa.si/?page=rss&q=subsplease+1080&c=0_0&f=0"
)

# Fetch the RSS feeds and extract titles
titles=""
for url in "${RSS_URLS[@]}"; do
    titles+="$(curl -s "$url" | xmlstarlet sel -t -m "//item" -v "concat(title, \"|\", link)" -n)"
done

# Check if there are any titles
if [[ -z $titles ]]; then
    echo "No titles found in the RSS feeds."
    exit 1
fi

# Display the titles using fzf and select one
selected_title=$(echo "$titles" | fzf --prompt="Select an entry to download: " --preview-window=hidden)

# Check if a title was selected
if [[ -z $selected_title ]]; then
    echo "No title selected. Exiting."
    exit 0
fi

selected_link=$(echo "$selected_title" | awk -F '|' '{print $2}')

# Download the selected torrent using aria2c
aria2c --summary-interval=0 --console-log-level=warn --seed-time=0 "$selected_link"

rm ./*.torrent

